name: Windows RDP via Tailscale (B)

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Run a short 10-minute test instead of ~6 hours"
        type: boolean
        default: false
  workflow_run:
    workflows: ["Windows RDP via Tailscale (A)"]
    types: [completed]

permissions:
  contents: read
  actions: write

concurrency:
  group: rdp-tailscale-chain
  cancel-in-progress: false

env:
  RUNTIME_MINUTES: ${{ inputs.test_mode && '10' || '355' }}
  TS_AUTHKEY: tskey-auth-kCBNtpbt3H11CNTRL-rJdYwx6bnR59Gj4ivN4DR5JKvahLZ5ML
  TS_API_KEY: Bearer tskey-api-k8k6TMrxJD21CNTRL-UZ4q4DdnFicBmuLEc4DqicCcr34WBQkrC
  TS_TAILNET: zatchati0@gmail.com
  GH_PAT: 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
  RDP_USER: Bullettemporary
  RDP_PASS: Bullet@12345
  TS_HOSTNAME: bullet

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Fast install Tailscale
        shell: pwsh
        run: |
          $url = 'https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe'
          $dst = "$env:TEMP\tailscale-setup.exe"
          Invoke-WebRequest -Uri $url -OutFile $dst -UseBasicParsing
          Start-Process -FilePath $dst -ArgumentList "/quiet" -Wait
          Start-Service Tailscale -ErrorAction SilentlyContinue

      - name: Enable RDP + user + firewall
        shell: pwsh
        run: |
          $u = $env:RDP_USER
          $p = $env:RDP_PASS
          $sec = ConvertTo-SecureString $p -AsPlainText -Force
          if (-not (Get-LocalUser -Name $u -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name $u -Password $sec -AccountNeverExpires -PasswordNeverExpires:$true
            Add-LocalGroupMember -Group Administrators -Member $u
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member $u
          } else {
            Set-LocalUser -Name $u -Password $sec -AccountNeverExpires:$true
            Enable-LocalUser -Name $u
          }
          Set-ItemProperty "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop" | Out-Null

      - name: PURGE tailnet devices (bullet*)
        shell: pwsh
        run: |
          $hdr = @{ Authorization = "$env:TS_API_KEY" }
          $tailnetEnc = [uri]::EscapeDataString($env:TS_TAILNET)
          $url = "https://api.tailscale.com/api/v2/tailnet/$tailnetEnc/devices"
          $pattern = '^(bullet)(?:-\d+)?$'
          try {
            $resp = Invoke-RestMethod -Method GET -Headers $hdr -Uri $url
            foreach ($d in $resp.devices) {
              $name = $d.hostname.ToLower()
              if ($name -match $pattern) {
                Invoke-RestMethod -Method DELETE -Headers $hdr -Uri ("https://api.tailscale.com/api/v2/device/{0}" -f $d.id) | Out-Null
                Write-Host "Deleted: $name"
              }
            }
          } catch { Write-Warning "Purge failed: $_" }

      - name: Tailscale up (permanent hostname)
        shell: pwsh
        run: |
          $ts = "$Env:ProgramFiles\Tailscale\tailscale.exe"
          if (-not (Test-Path $ts)) { $ts = "${Env:ProgramFiles(x86)}\Tailscale\tailscale.exe" }
          & $ts up --auth-key "$env:TS_AUTHKEY" --hostname "$env:TS_HOSTNAME" --accept-routes --accept-dns=false
          Start-Sleep 3
          $ipv4 = (& $ts ip -4 | Select-Object -First 1)
          $ipv6 = (& $ts ip -6 | Select-Object -First 1)
          $status = & $ts status --json | ConvertFrom-Json
          $fqdn = $status.Self.DNSName
          $derp = $status.Self.DERPRegionName
          "### RDP CONNECT (B)`n**Hostname**: $env:TS_HOSTNAME`n**IPv4**: $ipv4`n**IPv6**: $ipv6`n**MagicDNS**: $fqdn`n**DERP**: $derp`n**MSTSC**: mstsc /v:$env:TS_HOSTNAME`n**User**: $env:RDP_USER`n**Pass**: $env:RDP_PASS" | Out-File $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8

      - name: Keep alive until runtime, then dispatch A
        shell: pwsh
        env:
          PARTNER_FILE: windows-rdp-tailscale-A.yml
        run: |
          [int]$total = $env:RUNTIME_MINUTES
          $endAt = (Get-Date).AddMinutes($total)
          while ((Get-Date) -lt $endAt) {
            $minsLeft = [int]([math]::Ceiling(($endAt - (Get-Date)).TotalMinutes))
            Write-Host "[$(Get-Date -Format 'HH:mm:ss')] RDP alive.. ($minsLeft min left)"
            Start-Sleep -Seconds 60
          }
          Write-Host "Runtime done, dispatching partner (A)"
          Invoke-RestMethod -Method POST `
            -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$($env:PARTNER_FILE)/dispatches" `
            -Headers @{ Authorization = "token $env:GH_PAT"; "Accept"="application/vnd.github+json" } `
            -Body (@{ ref = "${{ github.ref_name }}" } | ConvertTo-Json)

      - name: Final purge bullet* (always)
        if: always()
        shell: pwsh
        run: |
          $hdr = @{ Authorization = "$env:TS_API_KEY" }
          $tailnetEnc = [uri]::EscapeDataString($env:TS_TAILNET)
          $url = "https://api.tailscale.com/api/v2/tailnet/$tailnetEnc/devices"
          $pattern = '^(bullet)(?:-\d+)?$'
          try {
            $resp = Invoke-RestMethod -Method GET -Headers $hdr -Uri $url
            foreach ($d in $resp.devices) {
              if ($d.hostname.ToLower() -match $pattern) {
                Invoke-RestMethod -Method DELETE -Headers $hdr -Uri ("https://api.tailscale.com/api/v2/device/{0}" -f $d.id) | Out-Null
                Write-Host "Deleted at exit: $($d.hostname)"
              }
            }
          } catch { Write-Warning "Final purge failed: $_" }
